/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.deSCribe;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int compass=0x7f020000;
        public static final int compass1=0x7f020001;
        public static final int confused=0x7f020002;
        public static final int icon=0x7f020003;
        public static final int mappin_blue=0x7f020004;
        public static final int mappin_red=0x7f020005;
        public static final int tile_0_0=0x7f020006;
        public static final int tile_0_1=0x7f020007;
        public static final int tile_0_2=0x7f020008;
        public static final int tile_1_0=0x7f020009;
        public static final int tile_1_1=0x7f02000a;
        public static final int tile_1_2=0x7f02000b;
        public static final int tile_2_0=0x7f02000c;
        public static final int tile_2_1=0x7f02000d;
        public static final int tile_2_2=0x7f02000e;
        public static final int tile_3_0=0x7f02000f;
        public static final int tile_3_1=0x7f020010;
        public static final int tile_3_2=0x7f020011;
        public static final int tommytrojan2=0x7f020012;
        public static final int usc=0x7f020013;
        public static final int usc1=0x7f020014;
    }
    public static final class id {
        public static final int Coarse=0x7f060009;
        public static final int Fine=0x7f060008;
        public static final int btnPath=0x7f060004;
        public static final int choice=0x7f06000a;
        public static final int detail=0x7f060006;
        public static final int etEnd=0x7f060002;
        public static final int go_button=0x7f060000;
        public static final int info_button=0x7f060001;
        public static final int mapview1=0x7f060005;
        public static final int menu=0x7f060007;
        public static final int tvPath=0x7f060003;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int main_compass=0x7f030001;
        public static final int main_details=0x7f030002;
        public static final int main_route=0x7f030003;
        public static final int radio=0x7f030004;
    }
    public static final class raw {
        public static final int nothing_to_delete=0x7f040000;
    }
    public static final class string {
        public static final int Coarse=0x7f050002;
        public static final int Fine=0x7f050000;
        public static final int app_name=0x7f050006;
        public static final int hello=0x7f050001;
        public static final int radio_clear=0x7f050005;
        public static final int radio_group_none=0x7f050004;
        public static final int radio_selection=0x7f050003;
    }
}
